/*
 * qetnaviv2dwaylandtransport.cpp — Wayland client transport for the etnaviv2d QPA.
 *
 * See header for design notes.
 */

#ifndef _GNU_SOURCE
#define _GNU_SOURCE   /* memfd_create() */
#endif

#include "qetnaviv2dwaylandtransport.h"

// Wayland protocol headers (generated by wayland-scanner into OUT_PWD)
#include "xdg-shell-client-protocol.h"
#include "linux-dmabuf-unstable-v1-client-protocol.h"
#include "ivi-application-client-protocol.h"

// libwayland-client
#include <wayland-client.h>

// linux input keycodes for the keyboard translation table
#include <linux/input-event-codes.h>

// libdrm (etnaviv BO dmabuf export)
#include <libdrm/etnaviv_drmif.h>
#include <xf86drm.h>
#include <drm_fourcc.h>
#include <fcntl.h>
#include <unistd.h>

// libetna2d
#include <etna2d.h>

#include <QAbstractEventDispatcher>
#include <QCoreApplication>
#include <QDebug>
#include <qpa/qwindowsysteminterface.h>

#include <cerrno>
#include <cstring>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/syscall.h>

QT_BEGIN_NAMESPACE

#define WL_DBG  if (qEnvironmentVariableIntValue("QT_ETNAVIV2D_DEBUG") > 0) qDebug()  << "[etnaviv2d|wl]"
#define WL_WARN qWarning() << "[etnaviv2d|wl]"
#define WL_INFO qInfo()    << "[etnaviv2d|wl]"

/* -----------------------------------------------------------------------
 * Construction / destruction
 * ----------------------------------------------------------------------- */
QEtnaviv2dWaylandTransport::QEtnaviv2dWaylandTransport(etna2d_device *etnaDev,
                                                       int            cardFd,
                                                       QObject       *parent)
    : QObject(parent)
    , m_etnadev(etnaDev)
    , m_cardFd(cardFd)
{
}

QEtnaviv2dWaylandTransport::~QEtnaviv2dWaylandTransport()
{
    disconnect();
}

/* -----------------------------------------------------------------------
 * connect() — bind Wayland globals, create surface role, wait for configure
 *
 * Shell auto-detection:
 *   If ivi_application is advertised → ivi-shell path (IVI surface role).
 *   Otherwise                        → kiosk-shell path (xdg_toplevel role).
 * ----------------------------------------------------------------------- */
bool QEtnaviv2dWaylandTransport::connect()
{
    /* 1. Open display */
    m_display = wl_display_connect(nullptr);
    if (!m_display) {
        WL_WARN << "wl_display_connect failed — is WAYLAND_DISPLAY set?";
        return false;
    }
    WL_INFO << "Connected to Wayland display";

    /* 2. Registry — bind compositor, xdg_wm_base, linux_dmabuf */
    m_registry = wl_display_get_registry(m_display);
    static const wl_registry_listener reg_listener = {
        registryGlobal,
        registryGlobalRemove
    };
    wl_registry_add_listener(m_registry, &reg_listener, this);

    /* Roundtrip 1: receive all globals */
    wl_display_roundtrip(m_display);

    if (!m_compositor || !m_dmabuf) {
        WL_WARN << "Required Wayland globals missing:"
                << "compositor=" << (m_compositor ? "ok" : "MISSING")
                << "linux_dmabuf=" << (m_dmabuf ? "ok" : "MISSING");
        disconnect();
        return false;
    }
    if (!m_xdgWmBase && !m_iviApp) {
        WL_WARN << "No shell global found (need xdg_wm_base or ivi_application)";
        disconnect();
        return false;
    }

    /* 3. Create wl_surface, then pick a surface role based on what the
     *    compositor advertised.  ivi_application takes priority when present
     *    (ivi-shell advertises both xdg_wm_base and ivi_application). */
    m_surface = wl_compositor_create_surface(m_compositor);

    if (m_iviApp) {
        /* ── IVI-shell path ────────────────────────────────────────────── */
        uint32_t ivi_id = 2000; /* default: Qt UI layer */
        const QByteArray env = qgetenv("QT_IVI_SURFACE_ID");
        if (!env.isEmpty()) {
            bool ok = false;
            uint32_t v = env.toUInt(&ok);
            if (ok) ivi_id = v;
        }

        static const ivi_surface_listener ivi_surf_listener = {
            iviSurfaceConfigure
        };
        m_iviSurface = ivi_application_surface_create(m_iviApp, ivi_id, m_surface);
        ivi_surface_add_listener(m_iviSurface, &ivi_surf_listener, this);

        /* ivi-shell configure arrives only after the first buffer commit
         * (unlike xdg_surface which fires on surface_create).  Pre-set the
         * geometry now so connect() can return immediately.  The actual
         * configure event (0×0) will arrive later and is a no-op here. */
        {
            int w = 1024, h = 600;
            const QByteArray geo = qgetenv("QT_IVI_GEOMETRY");
            if (!geo.isEmpty()) {
                const QList<QByteArray> parts = geo.split('x');
                if (parts.size() == 2) {
                    w = parts[0].toInt();
                    h = parts[1].toInt();
                }
            }
            m_outputGeometry = QRect(0, 0, w, h);
            m_configured = true;
        }

        /* Commit to trigger the configure event */
        wl_surface_commit(m_surface);

        WL_INFO << "ivi-shell mode: ivi_surface id=" << ivi_id;
    } else {
        /* ── kiosk-shell / xdg_toplevel path (existing) ─────────────────── */
        m_xdgSurface = xdg_wm_base_get_xdg_surface(m_xdgWmBase, m_surface);
        static const xdg_surface_listener surf_listener = {
            xdgSurfaceConfigure
        };
        xdg_surface_add_listener(m_xdgSurface, &surf_listener, this);

        m_xdgToplevel = xdg_surface_get_toplevel(m_xdgSurface);
        static const xdg_toplevel_listener tl_listener = {
            xdgToplevelConfigure,
            xdgToplevelClose,
            nullptr, /* configure_bounds (informational, ignored) */
            nullptr, /* wm_capabilities  (informational, ignored) */
        };
        xdg_toplevel_add_listener(m_xdgToplevel, &tl_listener, this);

        xdg_toplevel_set_title(m_xdgToplevel, "etnaviv2d-qt");
        xdg_toplevel_set_fullscreen(m_xdgToplevel, nullptr); /* any output */

        /* Initial commit to trigger the configure event */
        wl_surface_commit(m_surface);

        WL_INFO << "kiosk-shell mode: xdg_toplevel";
    }

    /* 4. Pump until xdg_surface configure arrives (the geometry roundtrip).
     * We pump synchronously here because the integration's initialize() needs
     * the output geometry before returning.  This is a one-time startup cost. */
    int timeout = 200; /* max 200 roundtrips (~20 ms) */
    while (!m_configured && timeout-- > 0)
        wl_display_roundtrip(m_display);

    if (!m_configured) {
        WL_WARN << "Timed out waiting for surface configure";
        disconnect();
        return false;
    }

    WL_INFO << "Surface configured, output geometry ="
            << m_outputGeometry.width() << "x" << m_outputGeometry.height();

    /* 5. Wire QSocketNotifier for all subsequent event delivery.
     *
     * NOTE: the notifier must NOT be created here during initializeHardware()
     * because QApplication has not yet started its event loop.  Creating a
     * QSocketNotifier before the event loop is running produces the warning
     * "Can only be used with threads started with QThread" and silently
     * disables it — wl_buffer.release events never arrive, the ring never
     * drains, and the frame-callback chain stalls.
     *
     * Instead, defer notifier creation to the first call to commitFrame()
     * (which happens after QApplication::exec() enters the event loop).
     * The same applies to the aboutToBlock connection.
     * See armNotifier() which is called lazily from commitFrame(). */

    m_connected = true;
    return true;
}

/* -----------------------------------------------------------------------
 * allocateRing() — allocate 3 ARGB8888/LINEAR BOs and export as wl_buffers
 * ----------------------------------------------------------------------- */
bool QEtnaviv2dWaylandTransport::allocateRing()
{
    if (!m_configured) {
        WL_WARN << "allocateRing: not yet configured";
        return false;
    }

    const int w = m_outputGeometry.width();
    const int h = m_outputGeometry.height();

    for (int i = 0; i < WL_RING_SIZE; ++i) {
        ArgbBo &slot = m_ring[i];

        /* Allocate dumb BO on card fd.
         * We use a dumb BO (not etna2d_surface_create) so we can PRIME-export it
         * as a dmabuf for Weston, then import it back into etnaviv for blitting.
         * This mirrors the KMS scanout BO path in qetnaviv2dscreen.cpp. */
        struct drm_mode_create_dumb creq = {};
        creq.width  = (uint32_t)w;
        creq.height = (uint32_t)h;
        creq.bpp    = 32;
        if (drmIoctl(m_cardFd, DRM_IOCTL_MODE_CREATE_DUMB, &creq)) {
            WL_WARN << "ring[" << i << "] CREATE_DUMB:" << strerror(errno);
            return false;
        }

        /* PRIME-export the dumb BO as a dmabuf fd */
        if (drmPrimeHandleToFD(m_cardFd, creq.handle,
                               DRM_CLOEXEC | DRM_RDWR, &slot.dmabuf_fd)) {
            WL_WARN << "ring[" << i << "] PRIME export:" << strerror(errno);
            struct drm_mode_destroy_dumb dreq = { .handle = creq.handle };
            drmIoctl(m_cardFd, DRM_IOCTL_MODE_DESTROY_DUMB, &dreq);
            return false;
        }

        /* Destroy the GEM handle — the dmabuf fd keeps the BO alive */
        {
            struct drm_mode_destroy_dumb dreq = { .handle = creq.handle };
            drmIoctl(m_cardFd, DRM_IOCTL_MODE_DESTROY_DUMB, &dreq);
        }

        /* Import into etnaviv so the GC520 DE can render into it */
        if (etna2d_surface_from_dmabuf(m_etnadev, slot.dmabuf_fd,
                                        w, h, creq.pitch,
                                        &slot.surf) != ETNA2D_OK
                || !slot.surf) {
            WL_WARN << "ring[" << i << "] etna2d_surface_from_dmabuf failed";
            close(slot.dmabuf_fd);
            slot.dmabuf_fd = -1;
            return false;
        }

        /* Create persistent wl_buffer via zwp_linux_dmabuf_v1 */
        zwp_linux_buffer_params_v1 *params =
            zwp_linux_dmabuf_v1_create_params(m_dmabuf);

        /* We need a fresh fd per params (kernel closes it after import) */
        int fd_dup = dup(slot.dmabuf_fd);
        if (fd_dup < 0) {
            WL_WARN << "ring[" << i << "] dup(dmabuf_fd):" << strerror(errno);
            etna2d_surface_destroy(slot.surf); slot.surf = nullptr;
            close(slot.dmabuf_fd); slot.dmabuf_fd = -1;
            zwp_linux_buffer_params_v1_destroy(params);
            return false;
        }

        zwp_linux_buffer_params_v1_add(params, fd_dup,
                                       0,               /* plane index */
                                       0,               /* offset */
                                       creq.pitch,
                                       DRM_FORMAT_MOD_LINEAR >> 32,
                                       DRM_FORMAT_MOD_LINEAR & 0xffffffff);

        /* Use create_immed (synchronous) — avoids an extra roundtrip */
        slot.wl_buf = zwp_linux_buffer_params_v1_create_immed(
                          params,
                          w, h,
                          DRM_FORMAT_ARGB8888,
                          0 /* flags */);
        zwp_linux_buffer_params_v1_destroy(params);
        close(fd_dup);

        if (!slot.wl_buf) {
            WL_WARN << "ring[" << i << "] zwp_linux_buffer_params create_immed failed";
            etna2d_surface_destroy(slot.surf); slot.surf = nullptr;
            close(slot.dmabuf_fd); slot.dmabuf_fd = -1;
            return false;
        }

        /* Wire the release callback so the ring back-pressure works */
        static const wl_buffer_listener buf_listener = { bufferRelease };
        wl_buffer_add_listener(slot.wl_buf, &buf_listener, &slot);

        slot.in_use.store(false);
        WL_DBG << "ring[" << i << "] surf=" << slot.surf
               << "dmabuf_fd=" << slot.dmabuf_fd
               << "wl_buf=" << slot.wl_buf;
    }

    WL_INFO << "ARGB ring allocated:" << WL_RING_SIZE << "x"
            << w << "x" << h << "ARGB8888/LINEAR";
    return true;
}

/* -----------------------------------------------------------------------
 * currentBo() — return the ring slot the blitter should render into
 * ----------------------------------------------------------------------- */
etna2d_surface *QEtnaviv2dWaylandTransport::currentBo()
{
    int slot = pickFree();
    if (slot < 0) {
        WL_WARN << "currentBo: all ring slots in use (back-pressure)";
        return nullptr;
    }
    m_currentSlot = slot;
    return m_ring[slot].surf;
}

/* -----------------------------------------------------------------------
 * armNotifier() — create QSocketNotifier lazily on first commitFrame().
 * Called after QApplication::exec() has entered the event loop so the
 * notifier is guaranteed to be associated with a running QThread.
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::armNotifier()
{
    if (m_notifier)
        return; /* already armed */

    m_notifier = new QSocketNotifier(wl_display_get_fd(m_display),
                                     QSocketNotifier::Read, this);
    QObject::connect(m_notifier, &QSocketNotifier::activated,
                     this, &QEtnaviv2dWaylandTransport::onWaylandReadable);

    /* Flush pending writes to compositor on every event-loop idle */
    if (QAbstractEventDispatcher *ed = QAbstractEventDispatcher::instance()) {
        QObject::connect(ed, &QAbstractEventDispatcher::aboutToBlock,
                         this, &QEtnaviv2dWaylandTransport::onAboutToBlock);
    }

    WL_DBG << "QSocketNotifier armed on fd" << wl_display_get_fd(m_display);
}

/* -----------------------------------------------------------------------
 * commitFrame() — called from BackingStore::flush() after blitting
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::commitFrame(etna2d_surface *bo)
{
    /* Arm the QSocketNotifier lazily on first commit — by this point
     * QApplication::exec() is running and the notifier will work correctly. */
    armNotifier();
    /* Find which slot was rendered into */
    int slot = -1;
    for (int i = 0; i < WL_RING_SIZE; ++i) {
        if (m_ring[i].surf == bo) { slot = i; break; }
    }
    if (slot < 0) {
        WL_WARN << "commitFrame: unknown BO surface pointer";
        return;
    }

    m_pendingCommitSlot = slot;
    m_dirty = true;

    if (!m_frameCallback) {
        /* No frame callback pending — first frame or compositor is idle.
         * Commit immediately to bootstrap the frame-callback chain. */
        doCommit(slot);
    }
    /* else: frame callback already armed; doCommit will be called when it fires */
}

/* -----------------------------------------------------------------------
 * doCommit() — attach + damage + commit, arm next frame callback
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::doCommit(int slot)
{
    ArgbBo &bo = m_ring[slot];
    bo.in_use.store(true);

    wl_surface_attach(m_surface, bo.wl_buf, 0, 0);
    wl_surface_damage_buffer(m_surface, 0, 0,
                              m_outputGeometry.width(),
                              m_outputGeometry.height());

    armFrameCallback();
    wl_surface_commit(m_surface);
    wl_display_flush(m_display);

    m_dirty = false;
    m_pendingCommitSlot = -1;

    WL_DBG << "committed slot" << slot;
}

/* -----------------------------------------------------------------------
 * armFrameCallback() — request wl_surface.frame for the next vblank
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::armFrameCallback()
{
    if (m_frameCallback)
        wl_callback_destroy(m_frameCallback);

    m_frameCallback = wl_surface_frame(m_surface);
    static const wl_callback_listener frame_listener = { frameCallback };
    wl_callback_add_listener(m_frameCallback, &frame_listener, this);
}

/* -----------------------------------------------------------------------
 * pickFree() — return first non-in_use slot
 * ----------------------------------------------------------------------- */
int QEtnaviv2dWaylandTransport::pickFree() const
{
    /* Prefer the slot after the current one (round-robin) */
    for (int i = 0; i < WL_RING_SIZE; ++i) {
        int s = (m_currentSlot + 1 + i) % WL_RING_SIZE;
        if (!m_ring[s].in_use.load())
            return s;
    }
    return -1;
}

/* -----------------------------------------------------------------------
 * disconnect() — release all Wayland + BO resources
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::disconnect()
{
    m_connected = false;

    delete m_notifier;
    m_notifier = nullptr;

    if (m_frameCallback) {
        wl_callback_destroy(m_frameCallback);
        m_frameCallback = nullptr;
    }

    /* Free ring BOs */
    for (int i = 0; i < WL_RING_SIZE; ++i) {
        ArgbBo &slot = m_ring[i];
        if (slot.wl_buf) { wl_buffer_destroy(slot.wl_buf); slot.wl_buf = nullptr; }
        if (slot.surf)   { etna2d_surface_destroy(slot.surf); slot.surf = nullptr; }
        if (slot.dmabuf_fd >= 0) { close(slot.dmabuf_fd); slot.dmabuf_fd = -1; }
        slot.in_use.store(false);
    }

    if (m_xdgToplevel) { xdg_toplevel_destroy(m_xdgToplevel); m_xdgToplevel = nullptr; }
    if (m_xdgSurface)  { xdg_surface_destroy(m_xdgSurface);   m_xdgSurface  = nullptr; }
    if (m_iviSurface)  { ivi_surface_destroy(m_iviSurface);    m_iviSurface  = nullptr; }
    if (m_surface)     { wl_surface_destroy(m_surface);        m_surface     = nullptr; }
    if (m_dmabuf)      { zwp_linux_dmabuf_v1_destroy(m_dmabuf); m_dmabuf     = nullptr; }
    if (m_xdgWmBase)   { xdg_wm_base_destroy(m_xdgWmBase);    m_xdgWmBase   = nullptr; }
    if (m_iviApp)      { ivi_application_destroy(m_iviApp);    m_iviApp      = nullptr; }
    /* input objects */
    if (m_keyboard)    { wl_keyboard_destroy(m_keyboard);      m_keyboard    = nullptr; }
    if (m_touch)       { wl_touch_destroy(m_touch);            m_touch       = nullptr; }
    if (m_pointer)     { wl_pointer_destroy(m_pointer);        m_pointer     = nullptr; }
    if (m_seat)        { wl_seat_destroy(m_seat);              m_seat        = nullptr; }
    /* Hardware cursor resources */
    if (m_cursorBuffer)  { wl_buffer_destroy(m_cursorBuffer);   m_cursorBuffer  = nullptr; }
    if (m_cursorSurface) { wl_surface_destroy(m_cursorSurface); m_cursorSurface = nullptr; }
    if (m_cursorShmData) { munmap(m_cursorShmData, m_cursorShmSize); m_cursorShmData = nullptr; }
    if (m_cursorShmFd >= 0) { close(m_cursorShmFd); m_cursorShmFd = -1; }
    m_cursorShmSize = 0;
    m_cursorBufferReady = false;
    if (m_shm)         { wl_shm_destroy(m_shm);                m_shm         = nullptr; }
    if (m_compositor)  { wl_compositor_destroy(m_compositor);  m_compositor  = nullptr; }
    if (m_registry)    { wl_registry_destroy(m_registry);      m_registry    = nullptr; }
    if (m_display)     { wl_display_disconnect(m_display);     m_display     = nullptr; }
}

/* -----------------------------------------------------------------------
 * QSocketNotifier slot — safe Wayland read/dispatch sequence
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::onWaylandReadable()
{
    /* prepare_read / read_events / dispatch_pending avoids the classic
     * fd-starvation deadlock where poll() returns readable but another thread
     * already consumed the data via dispatch(). */
    if (wl_display_prepare_read(m_display) == 0) {
        wl_display_read_events(m_display);
    }
    wl_display_dispatch_pending(m_display);
    wl_display_flush(m_display);
}

/* -----------------------------------------------------------------------
 * aboutToBlock slot — flush pending writes to compositor
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::onAboutToBlock()
{
    if (m_display)
        wl_display_flush(m_display);
}

/* -----------------------------------------------------------------------
 * wl_registry listeners
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::registryGlobal(void *data,
                                                 wl_registry *reg,
                                                 uint32_t name,
                                                 const char *iface,
                                                 uint32_t version)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);

    if (strcmp(iface, wl_compositor_interface.name) == 0) {
        self->m_compositor = static_cast<wl_compositor *>(
            wl_registry_bind(reg, name, &wl_compositor_interface,
                             qMin(version, 4u)));
    } else if (strcmp(iface, xdg_wm_base_interface.name) == 0) {
        self->m_xdgWmBase = static_cast<xdg_wm_base *>(
            wl_registry_bind(reg, name, &xdg_wm_base_interface,
                             qMin(version, 2u)));
        static const xdg_wm_base_listener wm_listener = { xdgWmBasePing };
        xdg_wm_base_add_listener(self->m_xdgWmBase, &wm_listener, self);
    } else if (strcmp(iface, zwp_linux_dmabuf_v1_interface.name) == 0) {
        self->m_dmabuf = static_cast<zwp_linux_dmabuf_v1 *>(
            wl_registry_bind(reg, name, &zwp_linux_dmabuf_v1_interface,
                             qMin(version, 3u)));
        static const zwp_linux_dmabuf_v1_listener dmabuf_listener = {
            dmabufFormat, dmabufModifier
        };
        zwp_linux_dmabuf_v1_add_listener(self->m_dmabuf, &dmabuf_listener, self);
    } else if (strcmp(iface, wl_seat_interface.name) == 0) {
        /* bind wl_seat (version 7 for axis_discrete; cap at avail) */
        self->m_seat = static_cast<wl_seat *>(
            wl_registry_bind(reg, name, &wl_seat_interface, qMin(version, 7u)));
        static const wl_seat_listener seat_listener = {
            seatCapabilities,
            seatName
        };
        wl_seat_add_listener(self->m_seat, &seat_listener, self);
    } else if (strcmp(iface, wl_shm_interface.name) == 0) {
        /* Hardware cursor: bind wl_shm for the 32x32 ARGB8888 cursor buffer */
        self->m_shm = static_cast<wl_shm *>(
            wl_registry_bind(reg, name, &wl_shm_interface, qMin(version, 1u)));
        static const wl_shm_listener shm_listener = { shmFormat };
        wl_shm_add_listener(self->m_shm, &shm_listener, self);
    } else if (strcmp(iface, ivi_application_interface.name) == 0) {
        /* bind ivi_application — present only under ivi-shell */
        self->m_iviApp = static_cast<ivi_application *>(
            wl_registry_bind(reg, name, &ivi_application_interface, 1u));
        WL_INFO << "ivi_application global found — ivi-shell mode";
    }
}

void QEtnaviv2dWaylandTransport::registryGlobalRemove(void * /*data*/,
                                                       wl_registry * /*reg*/,
                                                       uint32_t /*name*/)
{
    /* Globals disappearing at runtime is unexpected for a kiosk compositor. */
}

/* -----------------------------------------------------------------------
 * xdg_wm_base ping — must respond to keep the surface alive
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::xdgWmBasePing(void * /*data*/,
                                                xdg_wm_base *base,
                                                uint32_t serial)
{
    xdg_wm_base_pong(base, serial);
}

/* -----------------------------------------------------------------------
 * xdg_surface configure — acknowledge and record geometry
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::xdgSurfaceConfigure(void *data,
                                                      xdg_surface *surf,
                                                      uint32_t serial)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);
    xdg_surface_ack_configure(surf, serial);

    /* If the toplevel configure already set a size use it; otherwise fall
     * back to 1024×600 (the known panel size for this hardware). */
    if (!self->m_configured) {
        if (self->m_outputGeometry.isEmpty())
            self->m_outputGeometry = QRect(0, 0, 1024, 600);
        self->m_configured = true;
        WL_INFO << "xdg_surface configured:"
                << self->m_outputGeometry.width() << "x"
                << self->m_outputGeometry.height();
    }

    /* If we have a pending commit (dirty) and no frame callback is armed,
     * now is a good time to commit the first frame. */
    if (self->m_dirty && self->m_pendingCommitSlot >= 0 && !self->m_frameCallback)
        self->doCommit(self->m_pendingCommitSlot);
}

/* -----------------------------------------------------------------------
 * xdg_toplevel configure — compositor tells us the desired size
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::xdgToplevelConfigure(void *data,
                                                       xdg_toplevel * /*tl*/,
                                                       int32_t w, int32_t h,
                                                       struct wl_array * /*states*/)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);
    /* w==0, h==0 means "compositor doesn't care — use your preferred size" */
    if (w > 0 && h > 0)
        self->m_outputGeometry = QRect(0, 0, w, h);
    WL_DBG << "xdg_toplevel configure: " << w << "x" << h;
}

void QEtnaviv2dWaylandTransport::xdgToplevelClose(void * /*data*/,
                                                   xdg_toplevel * /*tl*/)
{
    WL_INFO << "xdg_toplevel close requested — quitting";
    QCoreApplication::quit();
}

/* -----------------------------------------------------------------------
 * ivi_surface configure
 *
 * ivi-shell sends this after surface_create.  The width/height are the
 * compositor-assigned dimensions (0 = client decides).  We treat this
 * the same as xdg_surface configure: record the geometry if provided,
 * set m_configured, then do a commit to complete the roundtrip.
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::iviSurfaceConfigure(void *data,
                                                      ivi_surface * /*surf*/,
                                                      int32_t width,
                                                      int32_t height)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);
    if (!self->m_configured) {
        /* ivi-shell always sends 0×0 — fall back to the known panel size.
         * A wl_output listener could supply the real size, but for this
         * hardware 1024×600 is fixed.  If QT_IVI_GEOMETRY is set use that. */
        if (width <= 0 || height <= 0) {
            const QByteArray geo = qgetenv("QT_IVI_GEOMETRY");
            if (!geo.isEmpty()) {
                const QList<QByteArray> parts = geo.split('x');
                if (parts.size() == 2) {
                    width  = parts[0].toInt();
                    height = parts[1].toInt();
                }
            }
            if (width <= 0 || height <= 0) {
                width  = 1024;
                height = 600;
            }
        }
        self->m_outputGeometry = QRect(0, 0, width, height);
        self->m_configured = true;
        WL_INFO << "ivi_surface configured:" << width << "x" << height;
    }

    if (self->m_dirty && self->m_pendingCommitSlot >= 0 && !self->m_frameCallback)
        self->doCommit(self->m_pendingCommitSlot);
}

/* -----------------------------------------------------------------------
 * zwp_linux_dmabuf_v1 listeners (informational only)
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::dmabufFormat(void * /*data*/,
                                               zwp_linux_dmabuf_v1 * /*dmabuf*/,
                                               uint32_t format)
{
    WL_DBG << "dmabuf supported format:" << Qt::hex << format;
}

void QEtnaviv2dWaylandTransport::dmabufModifier(void * /*data*/,
                                                 zwp_linux_dmabuf_v1 * /*dmabuf*/,
                                                 uint32_t format,
                                                 uint32_t modifier_hi,
                                                 uint32_t modifier_lo)
{
    Q_UNUSED(format); Q_UNUSED(modifier_hi); Q_UNUSED(modifier_lo);
}

/* -----------------------------------------------------------------------
 * wl_buffer release — slot is free again
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::bufferRelease(void *data, wl_buffer * /*buf*/)
{
    auto *slot = static_cast<ArgbBo *>(data);
    slot->in_use.store(false);
    WL_DBG << "wl_buffer released — slot back in ring";
}

/* -----------------------------------------------------------------------
 * wl_surface frame callback — vsync tick; commit pending frame if dirty
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::frameCallback(void *data,
                                                wl_callback *cb,
                                                uint32_t /*time*/)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);

    wl_callback_destroy(cb);
    self->m_frameCallback = nullptr;

    if (self->m_dirty && self->m_pendingCommitSlot >= 0) {
        self->doCommit(self->m_pendingCommitSlot);
    } else {
        /* Nothing to commit this vblank — re-arm so we stay in the chain */
        self->armFrameCallback();
        wl_surface_commit(self->m_surface);
        wl_display_flush(self->m_display);
    }
}

/* =======================================================================
 * wl_seat / wl_pointer / wl_touch / wl_keyboard
 * ======================================================================= */

/* -----------------------------------------------------------------------
 * wl_seat listeners
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::seatCapabilities(void *data,
                                                   wl_seat *seat,
                                                   uint32_t caps)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);

    /* wl_pointer */
    const bool hasPointer = caps & WL_SEAT_CAPABILITY_POINTER;
    if (hasPointer && !self->m_pointer) {
        self->m_pointer = wl_seat_get_pointer(seat);
        static const wl_pointer_listener ptr_listener = {
            pointerEnter, pointerLeave, pointerMotion,
            pointerButton, pointerAxis,
            pointerFrame, pointerAxisSource, pointerAxisStop, pointerAxisDiscrete,
            nullptr, /* axis_value120 (wl_pointer v8) — not used */
            nullptr, /* axis_relative_direction (wl_pointer v9) — not used */
        };
        wl_pointer_add_listener(self->m_pointer, &ptr_listener, self);
        WL_INFO << "wl_pointer bound";
    } else if (!hasPointer && self->m_pointer) {
        wl_pointer_destroy(self->m_pointer);
        self->m_pointer = nullptr;
    }

    /* wl_touch */
    const bool hasTouch = caps & WL_SEAT_CAPABILITY_TOUCH;
    if (hasTouch && !self->m_touch) {
        self->m_touch = wl_seat_get_touch(seat);
        static const wl_touch_listener touch_listener = {
            touchDown, touchUp, touchMotion, touchFrame, touchCancel,
            nullptr, /* shape (wl_touch v6) — not used */
            nullptr, /* orientation (wl_touch v6) — not used */
        };
        wl_touch_add_listener(self->m_touch, &touch_listener, self);
        WL_INFO << "wl_touch bound";
    } else if (!hasTouch && self->m_touch) {
        wl_touch_destroy(self->m_touch);
        self->m_touch = nullptr;
    }

    /* wl_keyboard */
    const bool hasKeyboard = caps & WL_SEAT_CAPABILITY_KEYBOARD;
    if (hasKeyboard && !self->m_keyboard) {
        self->m_keyboard = wl_seat_get_keyboard(seat);
        static const wl_keyboard_listener kb_listener = {
            keyboardKeymap, keyboardEnter, keyboardLeave,
            keyboardKey, keyboardModifiers, keyboardRepeatInfo
        };
        wl_keyboard_add_listener(self->m_keyboard, &kb_listener, self);
        WL_INFO << "wl_keyboard bound";
    } else if (!hasKeyboard && self->m_keyboard) {
        wl_keyboard_destroy(self->m_keyboard);
        self->m_keyboard = nullptr;
    }
}

void QEtnaviv2dWaylandTransport::seatName(void * /*data*/, wl_seat * /*seat*/,
                                           const char *name)
{
    WL_DBG << "wl_seat name:" << name;
}

/* -----------------------------------------------------------------------
 * wl_shm listener (informational only)
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::shmFormat(void * /*data*/, wl_shm * /*shm*/,
                                           uint32_t format)
{
    WL_DBG << "wl_shm supported format:" << Qt::hex << format;
}

/* -----------------------------------------------------------------------
 * createCursorBuffer() — hardware cursor support
 *
 * Builds a single 32x32 ARGB8888 wl_shm buffer (premultiplied alpha, as
 * required by the cursor-plane path) with a simple
 * solid-white, sharp-cornered arrowhead (rasterized via point-in-polygon),
 * and a dedicated cursor wl_surface to hold it.
 * Called lazily on first pointer enter; the buffer/surface persist for the
 * lifetime of the transport (attached once, never re-attached — only
 * wl_pointer_set_cursor() needs to be re-issued on every wl_pointer.enter,
 * per protocol requirements).
 *
 * Returns false on any allocation failure (memfd/mmap/shm pool) — the
 * caller (pointerEnter) simply skips wl_pointer_set_cursor() in that case,
 * leaving Weston's default (likely invisible/none) cursor in place. Never
 * crashes.
 * ----------------------------------------------------------------------- */
bool QEtnaviv2dWaylandTransport::createCursorBuffer()
{
    if (m_cursorBufferReady)
        return true;
    if (!m_shm || !m_compositor) {
        WL_WARN << "cursor: wl_shm or wl_compositor not bound yet";
        return false;
    }

    constexpr int kCursorSize = 32;   /* matches MA35 cursor plane fixed size */
    constexpr int kStride     = kCursorSize * 4; /* ARGB8888 */
    const size_t  size        = static_cast<size_t>(kStride) * kCursorSize;

    int fd = memfd_create("etnaviv2d-cursor", MFD_CLOEXEC);
    if (fd < 0) {
        WL_WARN << "cursor: memfd_create failed:" << strerror(errno);
        return false;
    }
    if (ftruncate(fd, static_cast<off_t>(size)) < 0) {
        WL_WARN << "cursor: ftruncate failed:" << strerror(errno);
        close(fd);
        return false;
    }

    void *data = mmap(nullptr, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (data == MAP_FAILED) {
        WL_WARN << "cursor: mmap failed:" << strerror(errno);
        close(fd);
        return false;
    }

    /* Paint a solid white, sharp-cornered arrowhead cursor: a concave
     * quadrilateral (P0 tip, P1 right wing, P2 inner notch, P3 bottom wing)
     * pointing toward the top-left corner, matching the mouse hotspot at
     * (0, 0). Rasterized with a point-in-polygon (ray-casting / even-odd
     * rule) test per pixel — no anti-aliasing, no rounded corners:
     * 0xFFFFFFFF (solid white) inside, 0x00000000 (transparent) outside. */
    auto *px = static_cast<uint32_t *>(data);
    std::memset(px, 0, size);

    static const int polyX[4] = { 2, 24, 12, 8 };
    static const int polyY[4] = { 2, 8, 12, 24 };
    constexpr int kNumVerts = 4;

    auto pointInPolygon = [](double px_, double py_) -> bool {
        bool inside = false;
        for (int i = 0, j = kNumVerts - 1; i < kNumVerts; j = i++) {
            const double xi = polyX[i], yi = polyY[i];
            const double xj = polyX[j], yj = polyY[j];
            const bool intersects =
                ((yi > py_) != (yj > py_)) &&
                (px_ < (xj - xi) * (py_ - yi) / (yj - yi) + xi);
            if (intersects)
                inside = !inside;
        }
        return inside;
    };

    for (int y = 0; y < kCursorSize; ++y) {
        for (int x = 0; x < kCursorSize; ++x) {
            /* sample at pixel center for a stable, symmetric rasterization */
            if (pointInPolygon(x + 0.5, y + 0.5))
                px[y * kCursorSize + x] = 0xFFFFFFFFu;
        }
    }

    wl_shm_pool *pool = wl_shm_create_pool(m_shm, fd, static_cast<int32_t>(size));
    if (!pool) {
        WL_WARN << "cursor: wl_shm_create_pool failed";
        munmap(data, size);
        close(fd);
        return false;
    }
    m_cursorBuffer = wl_shm_pool_create_buffer(pool, 0, kCursorSize, kCursorSize,
                                                kStride, WL_SHM_FORMAT_ARGB8888);
    wl_shm_pool_destroy(pool); /* buffer keeps its own ref on the pool's memory */
    if (!m_cursorBuffer) {
        WL_WARN << "cursor: wl_shm_pool_create_buffer failed";
        munmap(data, size);
        close(fd);
        return false;
    }

    m_cursorSurface = wl_compositor_create_surface(m_compositor);
    if (!m_cursorSurface) {
        WL_WARN << "cursor: wl_compositor_create_surface failed";
        wl_buffer_destroy(m_cursorBuffer);
        m_cursorBuffer = nullptr;
        munmap(data, size);
        close(fd);
        return false;
    }
    wl_surface_attach(m_cursorSurface, m_cursorBuffer, 0, 0);
    wl_surface_damage(m_cursorSurface, 0, 0, kCursorSize, kCursorSize);
    wl_surface_commit(m_cursorSurface);

    m_cursorShmData    = data;
    m_cursorShmFd      = fd;
    m_cursorShmSize    = size;
    m_cursorBufferReady = true;
    WL_INFO << "cursor:" << kCursorSize << "x" << kCursorSize
            << "ARGB8888 wl_shm cursor buffer created";
    return true;
}

/* -----------------------------------------------------------------------
 * wl_pointer listeners
 *
 * Weston delivers surface-local fixed-point coordinates.  We convert with
 * wl_fixed_to_double() and accumulate state until pointerButton/pointerAxis
 * where we fire QWindowSystemInterface events.
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::pointerEnter(void *data, wl_pointer *p,
                                               uint32_t serial,
                                               wl_surface * /*surf*/,
                                               int32_t sx, int32_t sy)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);
    self->m_pointerPos = QPointF(wl_fixed_to_double(sx), wl_fixed_to_double(sy));
    WL_DBG << "pointer enter" << self->m_pointerPos;

    /* Hardware cursor: (re-)issue set_cursor on every enter — cursor state
     * does not persist across leave/enter at the protocol level. Buffer is
     * created lazily once and reused for the transport's lifetime. */
    if (self->createCursorBuffer()) {
        wl_pointer_set_cursor(p, serial, self->m_cursorSurface, 0, 0);
    }
}

void QEtnaviv2dWaylandTransport::pointerLeave(void * /*data*/, wl_pointer * /*p*/,
                                               uint32_t /*serial*/,
                                               wl_surface * /*surf*/)
{
    WL_DBG << "pointer leave";
}

void QEtnaviv2dWaylandTransport::pointerMotion(void *data, wl_pointer * /*p*/,
                                                uint32_t /*time*/,
                                                int32_t sx, int32_t sy)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);
    self->m_pointerPos = QPointF(wl_fixed_to_double(sx), wl_fixed_to_double(sy));

    if (!self->m_window) return;
    QWindowSystemInterface::handleMouseEvent(
        self->m_window,
        self->m_pointerPos,
        self->m_pointerPos,        /* global = local for fullscreen */
        self->m_pointerButtons,
        Qt::NoButton,
        QEvent::MouseMove);
}

void QEtnaviv2dWaylandTransport::pointerButton(void *data, wl_pointer * /*p*/,
                                                uint32_t /*serial*/,
                                                uint32_t /*time*/,
                                                uint32_t button,
                                                uint32_t state)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);
    if (!self->m_window) return;

    /* Map linux BTN_* to Qt::MouseButton */
    Qt::MouseButton qtBtn = Qt::NoButton;
    switch (button) {
    case BTN_LEFT:   qtBtn = Qt::LeftButton;   break;
    case BTN_RIGHT:  qtBtn = Qt::RightButton;  break;
    case BTN_MIDDLE: qtBtn = Qt::MiddleButton; break;
    default: break;
    }
    if (qtBtn == Qt::NoButton) return;

    const bool pressed = (state == WL_POINTER_BUTTON_STATE_PRESSED);
    if (pressed)
        self->m_pointerButtons |= qtBtn;
    else
        self->m_pointerButtons &= ~qtBtn;

    const QEvent::Type evType = pressed ? QEvent::MouseButtonPress
                                        : QEvent::MouseButtonRelease;
    QWindowSystemInterface::handleMouseEvent(
        self->m_window,
        self->m_pointerPos,
        self->m_pointerPos,
        self->m_pointerButtons,
        qtBtn,
        evType);

    WL_DBG << "pointer button" << button << (pressed ? "pressed" : "released")
           << "pos" << self->m_pointerPos;
}

void QEtnaviv2dWaylandTransport::pointerAxis(void *data, wl_pointer * /*p*/,
                                              uint32_t /*time*/,
                                              uint32_t axis, int32_t value)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);
    if (!self->m_window) return;

    /* axis 0 = vertical scroll, axis 1 = horizontal scroll.
     * wl_fixed value is in surface units × 256; map to pixels / 10 for Qt. */
    const int delta = -wl_fixed_to_int(value); /* invert: Wayland down = positive */
    const QPoint angleDelta = (axis == WL_POINTER_AXIS_VERTICAL_SCROLL)
                               ? QPoint(0, delta * 12)
                               : QPoint(delta * 12, 0);

    QWindowSystemInterface::handleWheelEvent(
        self->m_window,
        self->m_pointerPos,
        self->m_pointerPos,
        QPoint(),       /* pixelDelta — not used */
        angleDelta,
        Qt::NoModifier);
}

/* wl_pointer v5+ frame/axis_source/axis_stop/axis_discrete: not needed but
 * the listener struct must be complete. */
void QEtnaviv2dWaylandTransport::pointerFrame(void * /*d*/, wl_pointer * /*p*/) {}
void QEtnaviv2dWaylandTransport::pointerAxisSource(void * /*d*/, wl_pointer * /*p*/, uint32_t /*s*/) {}
void QEtnaviv2dWaylandTransport::pointerAxisStop(void * /*d*/, wl_pointer * /*p*/, uint32_t /*t*/, uint32_t /*a*/) {}
void QEtnaviv2dWaylandTransport::pointerAxisDiscrete(void * /*d*/, wl_pointer * /*p*/, uint32_t /*a*/, int32_t /*v*/) {}

/* -----------------------------------------------------------------------
 * wl_touch listeners
 *
 * Weston sends pre-calibrated surface-local wl_fixed_t coordinates — the
 * libinput calibration matrix from /etc/udev/rules.d/libinput.rules has
 * already been applied.  No further transform needed.
 *
 * We accumulate touch points per-frame and flush them together on touchFrame()
 * so Qt's gesture recognisers see a coherent multi-touch snapshot.
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::touchDown(void *data, wl_touch * /*t*/,
                                            uint32_t /*serial*/, uint32_t /*time*/,
                                            wl_surface * /*surf*/,
                                            int32_t id, int32_t x, int32_t y)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);
    TouchPoint tp;
    tp.id    = id;
    tp.pos   = QPointF(wl_fixed_to_double(x), wl_fixed_to_double(y));
    tp.state = Qt::TouchPointPressed;

    /* If a point with this id already exists (driver re-uses id without sending
     * up — common on single-touch ABS devices), synthesize a release for it
     * first so Qt sees a clean press/release cycle. */
    for (int i = 0; i < self->m_touchPoints.size(); ++i) {
        if (self->m_touchPoints[i].id == id) {
            self->m_touchPoints[i].state = Qt::TouchPointReleased;
            /* flush the synthetic release immediately */
            touchFrame(data, nullptr);
            break;
        }
    }

    self->m_touchPoints.append(tp);
    WL_DBG << "touch down id=" << id << tp.pos;
}

void QEtnaviv2dWaylandTransport::touchUp(void *data, wl_touch * /*t*/,
                                          uint32_t /*serial*/, uint32_t /*time*/,
                                          int32_t id)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);
    for (auto &tp : self->m_touchPoints) {
        if (tp.id == id) { tp.state = Qt::TouchPointReleased; return; }
    }
    WL_DBG << "touch up id=" << id;
}

void QEtnaviv2dWaylandTransport::touchMotion(void *data, wl_touch * /*t*/,
                                              uint32_t /*time*/,
                                              int32_t id, int32_t x, int32_t y)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);
    const QPointF pos(wl_fixed_to_double(x), wl_fixed_to_double(y));
    for (auto &tp : self->m_touchPoints) {
        if (tp.id == id) { tp.pos = pos; tp.state = Qt::TouchPointMoved; return; }
    }
    WL_DBG << "touch motion id=" << id << pos;
}

void QEtnaviv2dWaylandTransport::touchFrame(void *data, wl_touch * /*t*/)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);
    if (!self->m_window || self->m_touchPoints.isEmpty()) return;

    /* Build QWindowSystemInterface touch point list */
    QList<QWindowSystemInterface::TouchPoint> qtPoints;
    for (const auto &tp : self->m_touchPoints) {
        QWindowSystemInterface::TouchPoint qtp;
        qtp.id       = tp.id;
        qtp.state    = tp.state;
        qtp.area     = QRectF(tp.pos, QSizeF(1, 1));
        qtp.pressure = (tp.state == Qt::TouchPointReleased) ? 0.0 : 1.0;
        /* normalizedPos removed in Qt 5.15; area in screen pixels is sufficient */
        qtPoints.append(qtp);
    }

    /* Use a static QTouchDevice pointer — created once */
    static QTouchDevice *s_touchDevice = []() {
        auto *dev = new QTouchDevice;
        dev->setName(QStringLiteral("wl_touch"));
        dev->setType(QTouchDevice::TouchScreen);
        dev->setCapabilities(QTouchDevice::Position | QTouchDevice::Pressure);
        QWindowSystemInterface::registerTouchDevice(dev);
        return dev;
    }();

    QWindowSystemInterface::handleTouchEvent(
        self->m_window, s_touchDevice, qtPoints);

    WL_DBG << "touch frame:" << qtPoints.size() << "points";

    /* Remove released points from the accumulator */
    self->m_touchPoints.erase(
        std::remove_if(self->m_touchPoints.begin(), self->m_touchPoints.end(),
                       [](const TouchPoint &tp) {
                           return tp.state == Qt::TouchPointReleased;
                       }),
        self->m_touchPoints.end());
}

void QEtnaviv2dWaylandTransport::touchCancel(void *data, wl_touch * /*t*/)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);

    /* Mark all tracked points as released and flush them through Qt so widgets
     * get a proper release event — critical on single-touch ABS drivers that
     * send cancel instead of up on lift. */
    for (auto &tp : self->m_touchPoints)
        tp.state = Qt::TouchPointReleased;

    if (!self->m_touchPoints.isEmpty())
        touchFrame(data, nullptr); /* reuse frame flush */

    self->m_touchPoints.clear();
    WL_DBG << "touch cancel";
}

/* -----------------------------------------------------------------------
 * wl_keyboard listeners
 *
 * We use a compact linux→Qt keycode lookup table instead of xkbcommon to
 * avoid the xkbcommon dependency on an embedded kiosk target.  The table
 * covers the keys that are realistic for a kiosk UI (navigation, digits,
 * function keys, common symbols).
 * ----------------------------------------------------------------------- */
void QEtnaviv2dWaylandTransport::keyboardKeymap(void * /*data*/,
                                                 wl_keyboard * /*kb*/,
                                                 uint32_t /*format*/,
                                                 int32_t fd, uint32_t /*size*/)
{
    /* We ignore the keymap fd and use the static linux→Qt table below.
     * Close the fd to avoid leaking it. */
    close(fd);
}

void QEtnaviv2dWaylandTransport::keyboardEnter(void * /*data*/,
                                                wl_keyboard * /*kb*/,
                                                uint32_t /*serial*/,
                                                wl_surface * /*surf*/,
                                                struct wl_array * /*keys*/)
{
    WL_DBG << "keyboard enter";
}

void QEtnaviv2dWaylandTransport::keyboardLeave(void * /*data*/,
                                                wl_keyboard * /*kb*/,
                                                uint32_t /*serial*/,
                                                wl_surface * /*surf*/)
{
    WL_DBG << "keyboard leave";
}

void QEtnaviv2dWaylandTransport::keyboardKey(void *data,
                                              wl_keyboard * /*kb*/,
                                              uint32_t /*serial*/,
                                              uint32_t /*time*/,
                                              uint32_t key,
                                              uint32_t state)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);
    if (!self->m_window) return;

    const Qt::Key qtKey = linuxKeyToQt(key);
    if (qtKey == Qt::Key_unknown) return;

    /* Build modifier flags from accumulated wl_keyboard.modifiers state */
    Qt::KeyboardModifiers mods = Qt::NoModifier;
    /* Bit positions: SHIFT=0, CAPS=1, CTRL=2, ALT=3 (standard Linux evdev) */
    const uint32_t m = self->m_keyModsDepressed | self->m_keyModsLatched
                       | self->m_keyModsLocked;
    if (m & (1u << 0)) mods |= Qt::ShiftModifier;
    if (m & (1u << 2)) mods |= Qt::ControlModifier;
    if (m & (1u << 3)) mods |= Qt::AltModifier;

    const bool pressed = (state == WL_KEYBOARD_KEY_STATE_PRESSED);
    QWindowSystemInterface::handleKeyEvent(
        self->m_window,
        pressed ? QEvent::KeyPress : QEvent::KeyRelease,
        qtKey,
        mods,
        QString() /* text — not decoded without xkbcommon */);

    WL_DBG << "key" << key << (pressed ? "pressed" : "released") << "→ Qt::Key" << qtKey;
}

void QEtnaviv2dWaylandTransport::keyboardModifiers(void *data,
                                                    wl_keyboard * /*kb*/,
                                                    uint32_t /*serial*/,
                                                    uint32_t mods_depressed,
                                                    uint32_t mods_latched,
                                                    uint32_t mods_locked,
                                                    uint32_t /*group*/)
{
    auto *self = static_cast<QEtnaviv2dWaylandTransport *>(data);
    self->m_keyModsDepressed = mods_depressed;
    self->m_keyModsLatched   = mods_latched;
    self->m_keyModsLocked    = mods_locked;
}

void QEtnaviv2dWaylandTransport::keyboardRepeatInfo(void * /*data*/,
                                                     wl_keyboard * /*kb*/,
                                                     int32_t /*rate*/,
                                                     int32_t /*delay*/)
{
    /* Key repeat is handled by Qt internally — ignore Weston's advertised rate. */
}

/* -----------------------------------------------------------------------
 * linuxKeyToQt() — compact linux evdev → Qt::Key lookup table
 * Covers navigation, digits, function keys, common symbols used in kiosk UIs.
 * ----------------------------------------------------------------------- */
Qt::Key QEtnaviv2dWaylandTransport::linuxKeyToQt(uint32_t k)
{
    /* clang-format off */
    switch (k) {
    /* Navigation */
    case KEY_UP:        return Qt::Key_Up;
    case KEY_DOWN:      return Qt::Key_Down;
    case KEY_LEFT:      return Qt::Key_Left;
    case KEY_RIGHT:     return Qt::Key_Right;
    case KEY_HOME:      return Qt::Key_Home;
    case KEY_END:       return Qt::Key_End;
    case KEY_PAGEUP:    return Qt::Key_PageUp;
    case KEY_PAGEDOWN:  return Qt::Key_PageDown;
    /* Control */
    case KEY_ENTER:
    case KEY_KPENTER:   return Qt::Key_Return;
    case KEY_ESC:       return Qt::Key_Escape;
    case KEY_BACKSPACE: return Qt::Key_Backspace;
    case KEY_DELETE:    return Qt::Key_Delete;
    case KEY_TAB:       return Qt::Key_Tab;
    case KEY_SPACE:     return Qt::Key_Space;
    /* Digits */
    case KEY_0:         return Qt::Key_0;
    case KEY_1:         return Qt::Key_1;
    case KEY_2:         return Qt::Key_2;
    case KEY_3:         return Qt::Key_3;
    case KEY_4:         return Qt::Key_4;
    case KEY_5:         return Qt::Key_5;
    case KEY_6:         return Qt::Key_6;
    case KEY_7:         return Qt::Key_7;
    case KEY_8:         return Qt::Key_8;
    case KEY_9:         return Qt::Key_9;
    /* Letters (uppercase Qt::Key_ values) */
    case KEY_A:         return Qt::Key_A;
    case KEY_B:         return Qt::Key_B;
    case KEY_C:         return Qt::Key_C;
    case KEY_D:         return Qt::Key_D;
    case KEY_E:         return Qt::Key_E;
    case KEY_F:         return Qt::Key_F;
    case KEY_G:         return Qt::Key_G;
    case KEY_H:         return Qt::Key_H;
    case KEY_I:         return Qt::Key_I;
    case KEY_J:         return Qt::Key_J;
    case KEY_K:         return Qt::Key_K;
    case KEY_L:         return Qt::Key_L;
    case KEY_M:         return Qt::Key_M;
    case KEY_N:         return Qt::Key_N;
    case KEY_O:         return Qt::Key_O;
    case KEY_P:         return Qt::Key_P;
    case KEY_Q:         return Qt::Key_Q;
    case KEY_R:         return Qt::Key_R;
    case KEY_S:         return Qt::Key_S;
    case KEY_T:         return Qt::Key_T;
    case KEY_U:         return Qt::Key_U;
    case KEY_V:         return Qt::Key_V;
    case KEY_W:         return Qt::Key_W;
    case KEY_X:         return Qt::Key_X;
    case KEY_Y:         return Qt::Key_Y;
    case KEY_Z:         return Qt::Key_Z;
    /* Function keys */
    case KEY_F1:        return Qt::Key_F1;
    case KEY_F2:        return Qt::Key_F2;
    case KEY_F3:        return Qt::Key_F3;
    case KEY_F4:        return Qt::Key_F4;
    case KEY_F5:        return Qt::Key_F5;
    case KEY_F6:        return Qt::Key_F6;
    case KEY_F7:        return Qt::Key_F7;
    case KEY_F8:        return Qt::Key_F8;
    case KEY_F9:        return Qt::Key_F9;
    case KEY_F10:       return Qt::Key_F10;
    case KEY_F11:       return Qt::Key_F11;
    case KEY_F12:       return Qt::Key_F12;
    /* Modifiers */
    case KEY_LEFTSHIFT:
    case KEY_RIGHTSHIFT: return Qt::Key_Shift;
    case KEY_LEFTCTRL:
    case KEY_RIGHTCTRL:  return Qt::Key_Control;
    case KEY_LEFTALT:
    case KEY_RIGHTALT:   return Qt::Key_Alt;
    default:             return Qt::Key_unknown;
    }
    /* clang-format on */
}

QT_END_NAMESPACE
